### PR TITLE
fixed storage of chatbox name; updated forge

### PR DESCRIPTION
**Pull request by TimGoll**
now a map reload doesn't clear the chatbox name, fixing #1 

There seems to be a rendering issue, because the block is just purple-black. I haven't changed anything except these two lines I've added. Do you know the reason?

### CODE REVIEW

**Comment by JoseluGames** [comment]
Thanks for the fix! I'm going to look now to the rendering issue and add you to the credits!

**Comment by TimGoll** [comment]
You don't need to add me to the credits. This was literally a one minute fix. But thank you. I'm honored :)

**Comment by JoseluGames** [comment]
It's way more time than what I've given to the issue hahaha

**Comment by TimGoll** [comment]
I wanted to add the mod to my new modpack and it annoyed me. So I fixed it by myself^^

**Pull request merged**
